name:                TBillAnalysis
version:             0.1.0.0
github:              "JAPJr/TBillAnalysis"
license:             BSD3
author:              "John Polo"
maintainer:          "polophysics@gmail.com"
copyright:           "John Polo"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JAPJr/TBillAnalysis#readme>

dependencies:
- base >= 4.7 && < 5
- time
- bytestring
- http-conduit
- numbers
- process
- boxes

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  TBillAnalysis-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TBillAnalysis

tests:
  TBillAnalysis-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TBillAnalysis
